import { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import userService from '../../../../../../services/UserService';
import { fetchClassifications, fetchStatuses, fetchAssetGroups, fetchMainTypes, fetchCategoryTypes } from '../../../../../../services/AssetService';
import { showError } from '../../../../../../components/shared/notification/toast';
import { initialAssetState, validateAssetForm } from '../constants/assetConstants';

export const useAssetForm = (show, asset = null) => {
  const [newAsset, setNewAsset] = useState(initialAssetState);
  const [karyawanList, setKaryawanList] = useState([]);
  const [classificationOptions, setClassificationOptions] = useState([]);
  const [karyawanOptions, setKaryawanOptions] = useState([]);
  const [loadingKaryawan, setLoadingKaryawan] = useState(false);
  const [loadingClassification, setLoadingClassification] = useState(false);
  const [attachments, setAttachments] = useState([]);
  const [existingDocuments, setExistingDocuments] = useState([]);
  const [errors, setErrors] = useState({});
  const [filteredKaryawanOptions, setFilteredKaryawanOptions] = useState([]);
  const [statusOptions, setStatusOptions] = useState([]);
  const [assetGroupOptions, setAssetGroupOptions] = useState([]);
  const [mainTypeOptions, setMainTypeOptions] = useState([]);
  const [categoryOptionsApi, setCategoryOptionsApi] = useState([]);
  const [subCategoryOptionsApi, setSubCategoryOptionsApi] = useState([]);
  const firstInputRef = useRef(null);
  const formRef = useRef(null);
  const karyawanCache = useRef(null);
  const classificationCache = useRef(null);
  const statusCache = useRef(null);
  const mainTypeCache = useRef(null);

  const debouncedSearchKaryawan = useCallback((searchTerm, setOptionsCallback) => {
    const timeoutId = setTimeout(() => {
      if (!searchTerm || searchTerm.length < 2) return setOptionsCallback(karyawanOptions);
      setOptionsCallback(karyawanOptions.filter((option) => option.label.toLowerCase().includes(searchTerm.toLowerCase())));
    }, 300);
    return () => clearTimeout(timeoutId);
  }, [karyawanOptions]);

  useEffect(() => {
    if (!show) return;
    setErrors({});
    if (asset) {
      const purchasePrice = asset.purchase_price_actual ?? asset.purchase_price ?? asset.purchase_price_plan ?? '';
      const purchasePricePlan = asset.purchase_price_plan ?? '';
      const tahunBeli = asset.tahunBeli || (asset.po_date_period ? asset.po_date_period.toString().slice(0, 4) : '');
      const tahunDepreciation = asset.tahunDepreciation || (asset.useful_life_year ? asset.useful_life_year.toString() : '') || '';
      const assetData = { ...initialAssetState, ...asset, purchase_price_plan: purchasePricePlan, purchase_price_actual: purchasePrice, tahunBeli, tahunDepreciation, noAsset: asset.noAsset || asset.asset_tag || '', nama: asset.nama || asset.asset_name || '', asset_main_type_id: asset.asset_main_type_id || '', category_id: asset.category_id || '', sub_category_id: asset.sub_category_id || '', asset_group_id: asset.asset_group_id || '', assetGroup: asset.assetGroup || asset.asset_group_name || '', classification_id: asset.classification_id || asset.classification || '', sub_category: asset.sub_category || asset.sub_category_name || asset.type || '', sub_category_name: asset.sub_category_name || asset.sub_category || asset.type || '', type: asset.type || '', nik: asset.nik || '', dept: asset.dept || asset.department || '', hostname: asset.hostname || '', status: asset.status || asset.current_status || 'Active', depreciation_end_date: asset.depreciation_end_date || '', mainIpAdress: asset.mainIpAdress || asset.ip_address || asset.main_ip_address || '', backupIpAdress: asset.backupIpAdress || '', accounting_asset_no: asset.accounting_asset_no || asset.asset_tag || '', acquisition_status: asset.acquisition_status || initialAssetState.acquisition_status, request_id: asset.request_id || '', invoice_number: asset.invoice_number || '' };
      assetData.accounting_asset_no = assetData.noAsset;
      setNewAsset(assetData); setExistingDocuments(asset.documents || []);
    } else { setNewAsset(initialAssetState); setExistingDocuments([]); }
    setAttachments([]); setTimeout(() => firstInputRef.current?.focus(), 100);
  }, [show, asset]);
  useEffect(() => { if (!show) return; const f=async()=>{ if(mainTypeCache.current){setMainTypeOptions(mainTypeCache.current);return;} try { const res=await fetchMainTypes(); const data=Array.isArray(res?.data)?res.data:[]; const options=data.map((mt)=>({value:String(mt.asset_main_type_id),label:mt.main_type_name,fieldName:'asset_main_type_id'})); mainTypeCache.current=options; setMainTypeOptions(options);} catch { setMainTypeOptions([{ value:'1',label:'UTAMA',fieldName:'asset_main_type_id' },{ value:'2',label:'CLIENT',fieldName:'asset_main_type_id' }]); } }; f(); }, [show]);
  useEffect(() => { if (!show || !newAsset.asset_main_type_id) { setCategoryOptionsApi([]); return; } const f=async()=>{ try { const res=await fetchCategoryTypes(null,newAsset.asset_main_type_id); const data=Array.isArray(res?.data)?res.data:[]; const unique=[]; const map=new Map(); data.forEach((item)=>{ if(!map.has(item.category_id)){ map.set(item.category_id,{ value:item.category_id, label:item.category, category_id:item.category_id }); unique.push(map.get(item.category_id)); } }); setCategoryOptionsApi(unique);} catch { setCategoryOptionsApi([]); } }; f(); }, [show, newAsset.asset_main_type_id]);
  useEffect(() => { if (!show || !newAsset.category_id) { setSubCategoryOptionsApi([]); return; } const f=async()=>{ try { const res=await fetchCategoryTypes(null,newAsset.asset_main_type_id,newAsset.category_id); const data=Array.isArray(res?.data)?res.data:[]; const subs=[]; data.forEach((item)=>{ if(Array.isArray(item.sub_categories)) item.sub_categories.forEach((sub)=>subs.push({ value: sub.sub_category_id, label: sub.sub_category_name, sub_category_id: sub.sub_category_id, category_id: item.category_id })); }); setSubCategoryOptionsApi(subs);} catch { setSubCategoryOptionsApi([]); } }; f(); }, [show, newAsset.category_id, newAsset.asset_main_type_id]);
  useEffect(() => { if (!show || !newAsset.sub_category_id) return; const f=async()=>{ try { const res=await fetchAssetGroups(null,null,newAsset.sub_category_id); const data=Array.isArray(res?.data)?res.data:[]; setAssetGroupOptions(data.map((g)=>({ value:g.asset_group_id || g.asset_group_name, label:g.asset_group_name, asset_group_id:g.asset_group_id }))); } catch { setAssetGroupOptions([]); } }; f(); }, [show, newAsset.sub_category_id]);
  useEffect(() => { if (!show) return; const f=async()=>{ if (karyawanCache.current){ const cached=karyawanCache.current.map((k)=>({ value:k.nik, label:`${k.nik} - ${k.nama}` })); setKaryawanList(karyawanCache.current); setKaryawanOptions(cached); setFilteredKaryawanOptions(cached); return; } setLoadingKaryawan(true); try { const response = await userService.getAllKaryawan(); const data = response.data || []; karyawanCache.current = data; setKaryawanList(data); const options = data.map((k)=>({ value:k.nik, label:`${k.nik} - ${k.nama}` })); setKaryawanOptions(options); setFilteredKaryawanOptions(options); } catch { showError('Gagal memuat data karyawan. Silakan refresh halaman.'); } finally { setLoadingKaryawan(false); } }; f(); }, [show]);
  useEffect(() => { if (!show) return; const f=async()=>{ if(statusCache.current){setStatusOptions(statusCache.current);return;} try { const res=await fetchStatuses(); const data=Array.isArray(res?.data)?res.data:[]; const options=data.filter((s)=>s.is_active!==false).map((s)=>({ value:s.status_name,label:s.status_name })); statusCache.current=options; setStatusOptions(options);} catch { setStatusOptions([]); } }; f(); }, [show]);
  useEffect(() => { if (!show) return; const subLabel=(newAsset.sub_category_name || newAsset.sub_category || newAsset.type || '').toLowerCase(); const isPC=subLabel==='pc' || subLabel.includes('pc'); if (!isPC){ setClassificationOptions([]); return; } if (classificationCache.current){ setClassificationOptions(classificationCache.current); return; } setLoadingClassification(true); fetchClassifications().then((res)=>{ const data=Array.isArray(res?.data)?res.data:[]; const options=data.map((c)=>({ value:c.classification_id,label:c.classification_name })); classificationCache.current=options; setClassificationOptions(options); }).catch(()=>{ showError('Gagal memuat classification. Silakan refresh halaman.'); setClassificationOptions([]); }).finally(()=>setLoadingClassification(false)); }, [show, newAsset.sub_category, newAsset.sub_category_name, newAsset.type]);
  const handleChange = useCallback((e)=>{ const { name, value } = e.target; let formattedValue = value; const baseAsset = { ...newAsset, [name]: formattedValue }; if (name === 'tahunBeli'){ const date = new Date(value); if (!isNaN(date.getTime())){ const year = date.getFullYear(); baseAsset[name]=value; baseAsset.po_date_period=`${year}01`; baseAsset.depreciation_end_date=`${year + 6}-12-31`; } } if (name === 'tahunDepreciation'){ const numValue = parseInt(value); if (value && (isNaN(numValue) || numValue < 1 || numValue > 30)){ setErrors((prev)=>({ ...prev, tahunDepreciation: 'Harus 1-30 tahun' })); formattedValue=value; } else { if (errors.tahunDepreciation) setErrors((prev)=>({ ...prev, tahunDepreciation: null })); formattedValue = numValue.toString(); } } if (name === 'noAsset' || name === 'hostname'){ formattedValue = value.toUpperCase(); baseAsset[name]=formattedValue; } if (name === 'noAsset') baseAsset.accounting_asset_no = formattedValue; setNewAsset(baseAsset); if (errors[name] && name !== 'tahunDepreciation') setErrors((prev)=>({ ...prev, [name]: null })); }, [errors, newAsset]);
  const handleSelectChange = useCallback((name, selectedOption)=>{ const option = typeof selectedOption === 'string' || typeof selectedOption === 'number' ? { value:selectedOption,label:String(selectedOption) } : selectedOption; const fieldName = name || selectedOption?.fieldName || 'unknown'; const value = option?.value ?? ''; const label = option?.label ?? ''; const assetGroupId = option?.asset_group_id || ''; setNewAsset((prev)=>({ ...prev, [fieldName]: value, ...(fieldName === 'assetGroup' ? { asset_group_id: assetGroupId } : {}), ...(fieldName === 'asset_main_type_id' ? { asset_main_type_name: label } : {}), ...(fieldName === 'sub_category_id' ? { sub_category: label, sub_category_name: label } : {}) })); if (errors[fieldName]) setErrors((prev)=>({ ...prev, [fieldName]: null })); if (fieldName === 'asset_main_type_id'){ setNewAsset((prev)=>({ ...prev, asset_main_type_id:value, asset_main_type_name:label, category:'', category_id:'', sub_category:'', sub_category_id:'', classification_id:'', assetGroup:'', asset_group_id:'' })); setCategoryOptionsApi([]); setSubCategoryOptionsApi([]); setAssetGroupOptions([]); setClassificationOptions([]); } else if (fieldName === 'category_id'){ setNewAsset((prev)=>({ ...prev, category_id:value, sub_category:'', sub_category_id:'', classification_id:'', assetGroup:'', asset_group_id:'' })); setSubCategoryOptionsApi([]); setAssetGroupOptions([]); setClassificationOptions([]); } else if (fieldName === 'sub_category_id'){ setNewAsset((prev)=>({ ...prev, sub_category_id:value, classification_id:'', assetGroup:'', asset_group_id:'' })); setClassificationOptions([]); setAssetGroupOptions([]); } else if (fieldName === 'nik'){ const selectedKaryawan = karyawanList.find((k) => k.nik === value); setNewAsset((prev)=>({ ...prev, nik:value, dept:selectedKaryawan?.dept || '' })); } }, [karyawanList, errors]);
  const handleFileChange = useCallback((e, alertWarning)=>{ const files = Array.from(e.target.files); const existingNames = new Set(attachments.map((a)=>a.name)); const existingDocNames = new Set(existingDocuments.map((d)=>d.original_name || d.file_name)); const newAttachments=[]; files.forEach((file)=>{ if(file.type !== 'application/pdf'){ alertWarning(`File ${file.name}: Hanya file PDF yang diperbolehkan`); return; } if(file.size > 10 * 1024 * 1024){ alertWarning(`File ${file.name}: Ukuran file maksimal 10MB`); return; } if(existingNames.has(file.name)){ alertWarning(`File ${file.name} sudah ada dalam daftar`); return; } if(existingDocNames.has(file.name)){ alertWarning(`File ${file.name} sudah ada di dokumen asset`); return; } newAttachments.push(file); existingNames.add(file.name); }); if(newAttachments.length > 0) setAttachments((prev)=>[...prev, ...newAttachments]); e.target.value=''; }, [attachments, existingDocuments]);
  const removeAttachment = useCallback((index) => setAttachments((prev) => prev.filter((_, i) => i !== index)), []);
  const getSelectValue = useCallback((options, value)=>{ if(!value) return null; const stringValue = String(value); const matchedOption = options.find((o)=>String(o.value)===stringValue); if(matchedOption) return matchedOption; return options.find((o)=>String(o.label).toLowerCase().includes(stringValue.toLowerCase())) || null; }, []);
  const validateForm = useCallback(()=>{ const newErrors = validateAssetForm(newAsset); setErrors(newErrors); return Object.keys(newErrors).length === 0; }, [newAsset]);
  const isPC = useMemo(() => (newAsset.sub_category?.toLowerCase() === 'pc' || newAsset.sub_category_name?.toLowerCase() === 'pc' || subCategoryOptionsApi.find((s) => s.sub_category_id === newAsset.sub_category_id || s.value === newAsset.sub_category_id)?.label?.toLowerCase() === 'pc'), [newAsset.sub_category, newAsset.sub_category_name, newAsset.sub_category_id, subCategoryOptionsApi]);
  return { firstInputRef, formRef, newAsset, setNewAsset, karyawanList, classificationOptions, karyawanOptions, filteredKaryawanOptions, loadingKaryawan, loadingClassification, attachments, existingDocuments, setExistingDocuments, errors, setErrors, statusOptions, assetGroupOptions, mainTypeOptions, categoryOptionsApi, subCategoryOptionsApi, isPC, getSelectValue, handleChange, handleSelectChange, handleFileChange, removeAttachment, validateForm, debouncedSearchKaryawan };
};
